name: CI Pipeline

on:
  pull_request: # Pull Request 생성 또는 업데이트 시 실행
    branches:
      # main 및 develop 브랜치로 제출된 PR에 이 워크플로우가 작동
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest # Ubuntu 최신 버전 환경에서 실행

    steps:
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3 # GitHub의 설정된 액션을 사용해 JDK 환경 구성
        with:
          distribution: 'temurin' # OpenJDK 배포판 사용
          java-version: 17 # JDK 17 버전 사용

      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3 # 레포지토리의 코드를 가상 환경에 가져옴

      # AWS CLI 구성 (Dynamic RDS Permissions 추가)
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      # GitHub Action Runner의 IP 가져오기
      - name: Get GitHub Action Runner IP
        id: get_runner_ip
        run: |
          echo "runner_ip=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      # RDS 보안 그룹에 GitHub Runner IP 추가
      - name: Add GitHub Runner IP to RDS security group
        env:
          RUNNER_IP: ${{ env.runner_ip }}
          SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 3306 \
            --cidr $RUNNER_IP/32
          echo "Added $RUNNER_IP to RDS security group"

      # 환경변수 세팅
      - name: Set environment variables from secrets
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.RDS_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.RDS_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: echo "Environment variables set!"

      # Gradle 캐싱
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 의존성 설치
      - name: Set up dependencies
        run: ./gradlew build

      # 테스트 실행
      - name: Run Tests
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.RDS_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.RDS_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: ./gradlew test

      # 테스트 실패시 디버깅 정보 출력
      - name: Display debug information
        if: failure()
        run: cat build/test-results/test/*.xml || true

      # RDS 보안 그룹에서 GitHub Runner IP 제거
      - name: Remove GitHub Runner IP from RDS security group
        if: always()  # 이전 step의 성공 여부와 관계없이 실행
        env:
          RUNNER_IP: ${{ env.runner_ip }}
          SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 3306 \
            --cidr $RUNNER_IP/32
          echo "Removed $RUNNER_IP from RDS security group"